# Generated by Django 4.2.6 on 2023-10-14 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_age_student_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='age',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='no_of_semester',
        ),
    ]
