# Generated by Django 4.2.6 on 2023-10-14 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_age_staff_dob_remove_student_no_of_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='qulification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='PARENT',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_replay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
