# Generated by Django 4.2.6 on 2023-10-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_complaint_complaint_staff_qulification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.CharField(default='', max_length=100),
        ),
    ]
