# Generated by Django 4.2.6 on 2023-10-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_complaint_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authority',
            old_name='gender',
            new_name='gendre',
        ),
        migrations.RemoveField(
            model_name='authority',
            name='qualification',
        ),
    ]
