# Generated by Django 4.2.6 on 2023-10-24 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=350)),
            ],
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_replay',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='PARENT',
        ),
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='LOGIN',
            field=models.ForeignKey(default='6', on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='PARENT',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.CreateModel(
            name='violence_included_face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
                ('VIOLENCE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.violence')),
            ],
        ),
    ]
