# Generated by Django 3.2.22 on 2023-10-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_student_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident_sub_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('INCIDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.incident')),
            ],
        ),
    ]
