# Generated by Django 3.2.22 on 2023-10-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_incident_sub_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident_sub_images',
            name='INCIDENT',
        ),
        migrations.AddField(
            model_name='incident_sub_images',
            name='VIOLENCE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.violence'),
            preserve_default=False,
        ),
    ]
