# Generated by Django 3.2.22 on 2023-10-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20231027_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(),
        ),
    ]
